version: "3.7"

services:

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ../:/var/www/html

  pgsql:
    build: ./pgsql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgsql/.data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    links:
      - nginx

  php:
    build: ./php
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ../:/var/www/html
    links:
      - pgsql